"""Verify the correct topic name matches the new schema."""
import requests
from ingestion.debezium_config import DebeziumConfigGenerator

KAFKA_CONNECT_URL = "http://72.61.233.209:8083"
CONNECTOR_NAME = "cdc-oracle_sf_p-ora-cdc_user"
ACTUAL_TOPIC = "oracle_sf_p.cdc_user.test"  # The topic that exists

print("=== VERIFYING CORRECT TOPIC NAME ===")
print(f"Actual topic (from Kafka UI): {ACTUAL_TOPIC}")
print(f"Schema: cdc_user (no special characters)")

# Get connector config
r = requests.get(f"{KAFKA_CONNECT_URL}/connectors/{CONNECTOR_NAME}/config")
config = r.json()

schema = config.get('table.include.list', '').split('.')[0] if '.' in config.get('table.include.list', '') else ''
table = config.get('table.include.list', '').split('.')[1] if '.' in config.get('table.include.list', '') else ''
server = config.get('database.server.name', '')
expected_topic_from_config = f"{server}.{schema}.{table}"

print(f"\n=== CONNECTOR CONFIG ===")
print(f"Schema in table.include.list: {schema}")
print(f"Table in table.include.list: {table}")
print(f"Server name: {server}")
print(f"Expected topic (from config): {expected_topic_from_config}")

# Check what get_topic_name generates
generated_topic = DebeziumConfigGenerator.get_topic_name(
    pipeline_name=server,
    schema=schema,
    table=table
)
print(f"Generated topic (from get_topic_name): {generated_topic}")

print(f"\n=== COMPARISON ===")
print(f"Actual topic: {ACTUAL_TOPIC}")
print(f"Expected from config: {expected_topic_from_config}")
print(f"Generated by code: {generated_topic}")

if expected_topic_from_config == ACTUAL_TOPIC:
    print(f"\n✓ Connector config matches actual topic!")
else:
    print(f"\n⚠ Mismatch! Connector expects: {expected_topic_from_config}")
    print(f"  But actual topic is: {ACTUAL_TOPIC}")

if generated_topic == ACTUAL_TOPIC:
    print(f"\n✓ Code generates correct topic name!")
else:
    print(f"\n⚠ Code generates wrong topic: {generated_topic}")
    print(f"  Should be: {ACTUAL_TOPIC}")

# Check connector status
print(f"\n=== CONNECTOR STATUS ===")
r2 = requests.get(f"{KAFKA_CONNECT_URL}/connectors/{CONNECTOR_NAME}/status")
status = r2.json()
print(f"State: {status.get('connector', {}).get('state')}")
print(f"Tasks: {len(status.get('tasks', []))}")

for i, task in enumerate(status.get('tasks', [])):
    print(f"Task {i}: {task.get('state')}")
    if task.get('trace'):
        print(f"  Error: {task.get('trace')[:400]}")

